# Generated by Django 6.0 on 2026-01-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
