# Generated by Django 6.0 on 2026-01-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorotimings',
            name='break_time',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='pomodorotimings',
            name='long_break_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='pomodorotimings',
            name='work_time',
            field=models.IntegerField(default=25),
        ),
    ]
