# Generated by Django 6.0 on 2026-01-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsApp', '0002_alter_pomodorotimings_break_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sheet',
        ),
    ]
